-- Execute no SQL Editor do Supabase antes de ativar o modo de produção.
create extension if not exists pgcrypto;

create table if not exists categories(id bigint generated by default as identity primary key, name text unique not null, created_at timestamptz default now());
create table if not exists suppliers(id bigint generated by default as identity primary key, name text unique not null, created_at timestamptz default now());
create table if not exists products(id bigint generated by default as identity primary key, name text unique not null, category_id bigint references categories(id), supplier_id bigint references suppliers(id), unit text default 'kg', stock numeric default 0, min_stock numeric default 10, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists stock_movements(id uuid primary key default gen_random_uuid(), product_id bigint references products(id) not null, type text check(type in ('entrada','saida','ajuste')) not null, quantity numeric not null, previous_stock numeric, new_stock numeric, movement_date date default current_date, note text, user_id uuid references auth.users(id), created_at timestamptz default now());
alter table stock_movements add column if not exists performed_by text;
create table if not exists orders(id bigint generated by default as identity primary key, product_id bigint references products(id), supplier_id bigint references suppliers(id), ordered_quantity numeric not null, reference text, created_at timestamptz default now());
create table if not exists receipts(id bigint generated by default as identity primary key, order_id bigint references orders(id), receipt_date date not null, quantity numeric not null, invoice_number text, user_id uuid references auth.users(id), created_at timestamptz default now());
-- Exemplo de RLS: em produção, crie políticas específicas para as duas usuárias autorizadas.
alter table categories enable row level security;
alter table suppliers enable row level security;
alter table products enable row level security;
alter table stock_movements enable row level security;
alter table orders enable row level security;
alter table receipts enable row level security;

-- Esta política permite acesso somente a pessoas autenticadas no Supabase Auth.
-- Para restringir por e-mail ou domínio, substitua auth.uid() por uma tabela de perfis.
drop policy if exists "authenticated users can read categories" on categories;
create policy "authenticated users can read categories" on categories for select to authenticated using (true);
drop policy if exists "authenticated users can manage categories" on categories;
create policy "authenticated users can manage categories" on categories for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read suppliers" on suppliers;
create policy "authenticated users can read suppliers" on suppliers for select to authenticated using (true);
drop policy if exists "authenticated users can manage suppliers" on suppliers;
create policy "authenticated users can manage suppliers" on suppliers for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read products" on products;
create policy "authenticated users can read products" on products for select to authenticated using (true);
drop policy if exists "authenticated users can manage products" on products;
create policy "authenticated users can manage products" on products for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read movements" on stock_movements;
create policy "authenticated users can read movements" on stock_movements for select to authenticated using (true);
drop policy if exists "authenticated users can insert movements" on stock_movements;
create policy "authenticated users can insert movements" on stock_movements for insert to authenticated with check (true);
drop policy if exists "authenticated users can read orders" on orders;
create policy "authenticated users can read orders" on orders for select to authenticated using (true);
drop policy if exists "authenticated users can manage orders" on orders;
create policy "authenticated users can manage orders" on orders for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read receipts" on receipts;
create policy "authenticated users can read receipts" on receipts for select to authenticated using (true);
drop policy if exists "authenticated users can manage receipts" on receipts;
create policy "authenticated users can manage receipts" on receipts for all to authenticated using (true) with check (true);
