import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Package, ArrowDownCircle, ArrowUpCircle, History, Truck, ClipboardList, Plus, Search, LogOut, Menu, X, AlertTriangle, CalendarDays, SlidersHorizontal, CheckCircle2, Info, LoaderCircle } from 'lucide-react';
import { isSupabaseConfigured, supabase } from './supabase';
import './styles.css';
import './alert-styles.css';
import ProductModal from './ProductModal';
import ProductActions from './ProductActions';
import { persistMovement } from './movementService';
import { loadCloudDataFromSupabase } from './cloudDataService';

const STORAGE = 'itabera-controle-alimentos-v2';
const initialProducts = [
  ['ABACATE', 'Hortifruti', 'COOPAFASP', 'kg'], ['ABOBRINHA', 'Hortifruti', 'AGROVIDA', 'kg'], ['ABÓBORA PESCOÇO', 'Hortifruti', 'AGROVIDA', 'kg'], ['ACELGA', 'Hortifruti', 'COOPAFASP', 'kg'], ['AÇUCAR', 'Alimentos Secos', 'MERCADO CENTRAL', 'kg'], ['ADOÇANTE', 'Alimentos Secos', 'STS', 'un'], ['ALFACE', 'Hortifruti', 'AGROVIDA', 'kg'], ['AMIDO DE MILHO', 'Alimentos Secos', 'FEC', 'kg'], ['ARROZ INTEGRAL', 'Alimentos Secos', 'FEC', 'kg'], ['AVEIA EM FARINHA', 'Alimentos Secos', 'FEC', 'kg'], ['AVEIA EM FLOCOS', 'Alimentos Secos', 'FEC', 'kg'], ['BANANA NANICA', 'Hortifruti', 'COOPAFASP', 'kg'], ['BANANA PRATA', 'Hortifruti', 'COOPAFASP', 'kg'], ['BATATA DOCE', 'Hortifruti', 'AGROVIDA', 'kg'], ['BETERRABA', 'Hortifruti', 'AGROVIDA', 'kg'], ['BRÓCOLIS', 'Hortifruti', 'AGROVIDA', 'kg'], ['CEBOLA', 'Hortifruti', 'AGROVIDA', 'kg'], ['CEBOLINHA', 'Hortifruti', 'AGROVIDA', 'kg'], ['CENOURA', 'Hortifruti', 'AGROVIDA', 'kg'], ['CHUCHU', 'Hortifruti', 'COOPAFASP', 'kg'], ['COUVE', 'Hortifruti', 'AGROVIDA', 'kg'], ['COUVE-FLOR', 'Hortifruti', 'COOPAFASP', 'kg'], ['FEIJÃO CARIOCA', 'Alimentos Secos', 'DA TERRA', 'kg'], ['LARANJA', 'Hortifruti', 'COOPAFASP', 'kg'], ['LEITE', 'Laticínios', 'ÁGUA PRETA', 'L'], ['MAÇÃ', 'Hortifruti', 'MARCIA CORREA', 'kg'], ['MANDIOCA', 'Hortifruti', 'AGROVIDA', 'kg'], ['MAMÃO FORMOSO', 'Hortifruti', 'LUIZ RAFAEL', 'kg'], ['MELANCIA', 'Hortifruti', 'AGROVIDA', 'kg'], ['MEXERICA', 'Hortifruti', 'COOPAFASP', 'kg'], ['MILHO VERDE', 'Hortifruti', 'AGROVIDA', 'kg'], ['MÚSCULO BOVINO', 'Carnes', 'FRIGOBOI', 'kg'], ['PATINHO EM CUBOS', 'Carnes', 'FRIGOBOI', 'kg'], ['PATINHO EM ISCAS', 'Carnes', 'FRIGOBOI', 'kg'], ['PATINHO MOIDO', 'Carnes', 'FRIGOBOI', 'kg'], ['PEITO DE FRANGO EM CUBOS', 'Carnes', 'FRIGOBOI', 'kg'], ['PEPINO', 'Hortifruti', 'AGROVIDA', 'kg'], ['PERNIL SUINO EM CUBOS', 'Carnes', 'FRIGOBOI', 'kg'], ['PITAYA', 'Hortifruti', 'COOPAFASP', 'kg'], ['REQUEIJÃO', 'Laticínios', 'ÁGUA PRETA', 'kg'], ['REPOLHO', 'Hortifruti', 'AGROVIDA', 'kg'], ['SALSINHA', 'Hortifruti', 'AGROVIDA', 'kg'], ['SOBRECOXA EM CUBOS', 'Carnes', 'FRIGOBOI', 'kg'], ['TOMATE', 'Hortifruti', 'COOPAFASP', 'kg']
].sort((a, b) => a[0].localeCompare(b[0], 'pt-BR')).map((p, i) => ({ id: i + 1, name: p[0], category: p[1], supplier: p[2], unit: p[3], stock: 0, minStock: 10 }));
const initialOrders = [
  { product: 'MÚSCULO BOVINO', ordered: 800, receipts: [['2026-06-03', 108], ['2026-06-11', 74], ['2026-06-18', 70], ['2026-06-25', 156]] },
  { product: 'PATINHO EM CUBOS', ordered: 1000, receipts: [['2026-06-10', 264], ['2026-06-18', 188], ['2026-06-25', 68]] },
  { product: 'PATINHO EM ISCAS', ordered: 800, receipts: [['2026-06-03', 304], ['2026-06-11', 228], ['2026-06-25', 250]] },
  { product: 'PATINHO MOIDO', ordered: 1500, receipts: [['2026-06-03', 396], ['2026-06-10', 396], ['2026-06-11', 324], ['2026-06-25', 560]] },
  { product: 'SOBRECOXA EM CUBOS', ordered: 1500, receipts: [['2026-06-03', 449], ['2026-06-10', 449], ['2026-06-11', 384], ['2026-06-18', 218]] },
  { product: 'PERNIL SUINO EM CUBOS', ordered: 1500, receipts: [['2026-06-03', 591], ['2026-06-10', 591], ['2026-06-18', 318]] },
  { product: 'PEITO DE FRANGO EM CUBOS', ordered: 1000, receipts: [['2026-06-03', 416], ['2026-06-10', 416], ['2026-06-18', 290]] }
];
function load() { try { return JSON.parse(localStorage.getItem(STORAGE)) || { products: [], movements: [], orders: [] } } catch { return { products: [], movements: [], orders: [] } } }
function App() {
  const [data, setData] = useState(load); const [page, setPage] = useState('dashboard'); const [search, setSearch] = useState(''); const [modal, setModal] = useState(null); const [menu, setMenu] = useState(false); const [logged, setLogged] = useState(!isSupabaseConfigured); const [user, setUser] = useState(''); const [loading, setLoading] = useState(isSupabaseConfigured); const [toast, setToast] = useState(null);
  useEffect(() => localStorage.setItem(STORAGE, JSON.stringify(data)), [data]);
  useEffect(() => { let active = true; if (!isSupabaseConfigured) { setLoading(false); return; } const start = async () => { const { data: sessionData } = await supabase.auth.getSession(); if (!active) return; if (sessionData.session) { setUser(sessionData.session.user.email || 'Usuária'); setLogged(true); await loadCloudData(setData, setToast) } else setLogged(false); setLoading(false) }; start(); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { if (session) { setUser(session.user.email || 'Usuária'); setLogged(true) } else { setLogged(false); setUser('') } }); return () => { active = false; listener.subscription.unsubscribe() }; }, []);
  const notify = (message, type = 'success') => { setToast({ message, type }); window.setTimeout(() => setToast(null), 4200) };
  const refreshData = async () => { if (isSupabaseConfigured) await loadCloudDataNew(setData, setToast); };
  const loadCloudDataNew = async (updateData, updateToast) => { const result = await loadCloudDataFromSupabase(supabase); if (result.error) { updateToast({ message: result.error, type: 'error' }); return; } if (result.warning) updateToast({ message: result.warning, type: 'error' }); updateData(current => ({ ...current, ...result.data, movements: result.data.movements.map(movement => ({ ...movement, user: !movement.user || movement.user === 'Usuária' || movement.user === 'Autor não informado' ? (user || 'Login atual') : movement.user })) })); };
  useEffect(() => { if (isSupabaseConfigured && logged && user) loadCloudDataNew(setData, setToast); }, [logged, user]);
  const saveMovement = async (form) => { const product = data.products.find(item => item.id === Number(form.productId)); if (!product) return; const session = isSupabaseConfigured ? (await supabase.auth.getSession()).data.session : null; const result = await persistMovement({ supabase: isSupabaseConfigured ? supabase : null, product, form, userId: session?.user?.id, performedBy: user || session?.user?.email || 'Usuária' }); if (result.error) { notify(result.error, 'error'); return; } setData(current => ({ ...current, products: current.products.map(item => item.id === product.id ? { ...item, stock: result.nextStock } : item), movements: [result.movement, ...current.movements] })); setModal(null); notify('Movimentação registrada com sucesso.'); };
  const addProduct = async (form) => { const name = form.name.trim().toUpperCase(); const category = (form.category || 'Sem categoria').trim(); const supplier = (form.supplier || 'Sem fornecedor').trim(); const stock = Number(form.stock || 0); const minStock = Number(form.minStock || 10); if (!name) { notify('Informe o nome do produto.', 'error'); return; } if (isSupabaseConfigured) { const { data: categoryRow, error: categoryError } = await supabase.from('categories').upsert({ name: category }, { onConflict: 'name' }).select('id,name').single(); if (categoryError) { notify('Não foi possível salvar a categoria: ' + categoryError.message, 'error'); return; } const { data: supplierRow, error: supplierError } = await supabase.from('suppliers').upsert({ name: supplier }, { onConflict: 'name' }).select('id,name').single(); if (supplierError) { notify('Não foi possível salvar o fornecedor: ' + supplierError.message, 'error'); return; } let { data: productRow, error: productError } = await supabase.from('products').insert({ name, category_id: categoryRow.id, supplier_id: supplierRow.id, unit: form.unit || 'kg', stock, min_stock: minStock, active: true }).select('*, categories(name), suppliers(name)').single(); if (productError?.code === '23505') { const { data: existing, error: existingError } = await supabase.from('products').select('id,stock').eq('name', name).single(); if (existingError) { notify('Já existe um produto com esse nome, mas não foi possível carregá-lo.', 'error'); return; } const restored = await supabase.from('products').update({ category_id: categoryRow.id, supplier_id: supplierRow.id, unit: form.unit || 'kg', min_stock: minStock, active: true, updated_at: new Date().toISOString() }).eq('id', existing.id).select('*, categories(name), suppliers(name)').single(); productRow = restored.data; productError = restored.error; } if (productError) { notify('Não foi possível salvar o produto: ' + productError.message, 'error'); return; } const product = { ...productRow, category: categoryRow.name, supplier: supplierRow.name, minStock: Number(productRow.min_stock), stock: Number(productRow.stock), unit: productRow.unit }; setData(current => ({ ...current, products: [...current.products.filter(item => item.id !== product.id), product].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')) })); } else { setData(current => ({ ...current, products: [...current.products, { id: Date.now(), name, category, supplier, unit: form.unit || 'kg', stock, minStock }].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')) })); } setModal(null); notify('Produto salvo com sucesso.'); };
  const legacySaveMovement = async (form) => { let p = data.products.find(x => x.id === Number(form.productId)); if (!p) return; if (isSupabaseConfigured) { const { data: latest, error: latestError } = await supabase.from('products').select('id,name,stock,unit,supplier_id,suppliers(name)').eq('id', p.id).single(); if (latestError) { notify('Não foi possível consultar o estoque atual.', 'error'); return; } p = { ...p, ...latest, supplier: latest.suppliers?.name || p.supplier }; } const qty = Number(form.quantity); const currentStock = Number(p.stock || 0); if (!Number.isFinite(qty) || qty <= 0) { notify('Informe uma quantidade válida.', 'error'); return; } if (form.type === 'saida' && qty > currentStock) { notify(`A saída solicitada (${fmt(qty)}) é maior que o estoque atual (${fmt(currentStock)}).`, 'error'); return; } const delta = form.type === 'entrada' ? qty : form.type === 'saida' ? -qty : qty - currentStock; const nextStock = Math.max(0, currentStock + delta); const products = data.products.map(x => x.id === p.id ? { ...x, stock: nextStock } : x); const movement = { id: crypto.randomUUID(), date: form.date || new Date().toISOString().slice(0, 10), time: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }), product: p.name, type: form.type, quantity: qty, delta, user: user || 'Usuária', note: form.note || '', supplier: p.supplier }; if (isSupabaseConfigured) { const { error } = await supabase.from('stock_movements').insert({ id: movement.id, product_id: p.id, type: form.type, quantity: qty, previous_stock: currentStock, new_stock: nextStock, movement_date: movement.date, note: movement.note }); if (error) { notify('Não foi possível salvar no Supabase. Verifique as políticas RLS.', 'error'); return; } const { error: updateError } = await supabase.from('products').update({ stock: nextStock, updated_at: new Date().toISOString() }).eq('id', p.id); if (updateError) { notify('Movimentação salva, mas o estoque não foi atualizado.', 'error'); return; } } setData(current => ({ ...current, products, movements: [movement, ...current.movements] })); setModal(null); notify('Movimentação registrada com sucesso.'); };
  if (loading) return <div className="loadingScreen"><LoaderCircle className="spin" size={34} /><b>Conectando ao ambiente seguro…</b><span>Estamos preparando seus dados.</span></div>;
  if (!logged) return <Login onLogin={(name) => { setUser(name); setLogged(true) }} onError={notify} />;
  const nav = [['dashboard', 'Dashboard', LayoutDashboard], ['products', 'Produtos', Package], ['stock', 'Estoque', ClipboardList], ['entrada', 'Entradas', ArrowDownCircle], ['saida', 'Saídas', ArrowUpCircle], ['weekly', 'Controle Semanal', CalendarDays], ['monthly', 'Controle Mensal', SlidersHorizontal], ['history', 'Histórico', History], ['suppliers', 'Fornecedores', Truck]];
  const content = () => { switch (page) { case 'dashboard': return <ModernDashboard data={data} onPage={setPage} />; case 'products': return <Products products={data.products} search={search} setSearch={setSearch} onNew={() => setModal({ type: 'newProduct' })} onMove={(type, id) => setModal({ type, productId: id })} onProductChange={refreshData} />; case 'stock': return <Stock products={data.products} onMove={(type, id) => setModal({ type, productId: id })} onProductChange={refreshData} />; case 'entrada': return <MovementPage type="entrada" movements={data.movements} onNew={() => setModal({ type: 'entrada' })} />; case 'saida': return <MovementPage type="saida" movements={data.movements} onNew={() => setModal({ type: 'saida' })} />; case 'weekly': return <Weekly orders={data.orders} />; case 'monthly': return <Monthly movements={data.movements} />; case 'history': return <HistoryPage movements={data.movements} />; case 'suppliers': return <Suppliers products={data.products} />; default: return null } };
  return <div className="app"><aside className={menu ? 'open' : ''}><div className="brand"><img src="/logo-prefeitura.png" /><div><b>Controle de Alimentação</b><small>Prefeitura de Itaberá</small></div><button className="icon mobile" onClick={() => setMenu(false)}><X /></button></div>{nav.map(([id, label, Icon]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => { setPage(id); setMenu(false) }}><Icon size={19} />{label}</button>)}<div className="sideBottom"><span>Logada como</span><b>{user}</b><button onClick={async () => { if (isSupabaseConfigured) await supabase.auth.signOut(); setLogged(false) }}><LogOut size={18} /> Sair</button></div></aside><main><header><button className="icon mobile" onClick={() => setMenu(true)}><Menu /></button><div><h1>{nav.find(n => n[0] === page)?.[1]}</h1><p>Gestão de estoque e recebimento de alimentos</p></div><div className="shared">● {isSupabaseConfigured ? 'Dados sincronizados' : 'Modo local'}</div></header>{content()}</main>{modal && <ProductModal modal={modal} products={data.products} onClose={() => setModal(null)} onSave={legacySaveMovement} onAddProduct={addProduct} />}{toast && <Toast {...toast} />}</div>
}
function Login({ onLogin, onError }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const submit = async () => { if (!email.trim() || !password) { onError('Informe e-mail e senha.', 'error'); return; } if (!isSupabaseConfigured) { onLogin(email.trim()); return; } setBusy(true); const { error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); setBusy(false); if (error) onError('E-mail ou senha inválidos.', 'error'); }; return <div className="login"><div className="loginCard"><img src="/logo-prefeitura.png" /><span className="eyebrow">ACESSO RESTRITO</span><h1>Controle de Alimentação</h1><p>Gestão de estoque e recebimento</p><label>E-mail<input type="email" placeholder="funcionaria@it“abera.sp.gov.br" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Senha<input type="password" placeholder="Sua senha" value={password} onChange={e => setPassword(e.target.value)} onKeyDown={e => e.key === 'Enter' && submit()} /></label><button onClick={submit} disabled={busy}>{busy ? <><LoaderCircle className="spin" size={18} /> Validando…</> : 'Entrar'}</button><small>{isSupabaseConfigured ? 'Acesso protegido pelo Supabase Auth.' : 'Modo demonstração local: preencha qualquer nome e senha.'}</small></div></div> }
async function loadCloudData(setData, setToast) { const [{ data: products, error: productsError }, { data: movements, error: movementsError }, { data: orders, error: ordersError }] = await Promise.all([supabase.from('products').select('*, categories(name), suppliers(name)').eq('active', true).order('name'), supabase.from('stock_movements').select('*, products(name, suppliers(name))').order('created_at', { ascending: false }), supabase.from('orders').select('*, products(name), suppliers(name), receipts(*)').order('created_at', { ascending: false })]); if (productsError) { setToast({ message: `Não foi possível carregar os produtos: ${productsError.message}`, type: 'error' }); return; } if (movementsError || ordersError) setToast({ message: 'Produtos carregados. Algumas informações de relatórios ainda não puderam ser carregadas.', type: 'error' }); setData(current => ({ ...current, products: (products || []).map(p => ({ ...p, category: p.categories?.name || 'Sem categoria', supplier: p.suppliers?.name || 'Sem fornecedor', minStock: Number(p.min_stock || 0), stock: Number(p.stock || 0), unit: p.unit || 'un' })), movements: movementsError ? [] : (movements || []).map(m => ({ id: m.id, date: m.movement_date, time: new Date(m.created_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }), product: m.products?.name || 'Produto removido', type: m.type, quantity: Number(m.quantity), delta: Number(m.new_stock || 0) - Number(m.previous_stock || 0), user: 'Usuária', note: m.note || '', supplier: m.products?.suppliers?.name || '' })), orders: ordersError ? [] : (orders || []).map(o => ({ product: o.products?.name || 'Produto não identificado', ordered: Number(o.ordered_quantity || 0), receipts: (o.receipts || []).map(r => [r.receipt_date, Number(r.quantity || 0)]) })) })); }
function Toast({ message, type }) { return <div className={'toast ' + type}>{type === 'error' ? <AlertTriangle size={19} /> : <CheckCircle2 size={19} />}<span>{message}</span></div> }
const fmt = n => new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 }).format(n);
function ModernDashboard({ data, onPage }) { const low = data.products.filter(p => p.stock > 0 && p.stock <= p.minStock).length; const cats = new Set(data.products.map(p => p.category)).size; const recent = data.movements.slice(0, 5); const hasData = data.products.length > 0 || data.movements.length > 0; return <><section className="dashboardHero"><div><span className="heroKicker">CENTRAL DE CONTROLE</span><h2>Visão geral do estoque</h2><p>Acompanhe produtos, entradas e saídas em um só lugar.</p></div><button className="heroAction" onClick={() => onPage('entrada')}><ArrowDownCircle size={18} /> Registrar entrada</button></section><section className="cards"><Card title="Produtos cadastrados" value={data.products.length} icon={Package} /><Card title="Categorias" value={cats} icon={ClipboardList} /><Card title="Estoque baixo" value={low} icon={AlertTriangle} /><Card title="Movimentações" value={data.movements.length} icon={History} /></section>{!hasData ? <div className="emptyDashboard"><div className="emptyIcon"><Package size={30} /></div><h2>Seu controle começa aqui</h2><p>Ainda não há produtos ou movimentações cadastrados. Adicione um produto ou registre a primeira entrada para começar.</p><div className="emptyActions"><button className="primary" onClick={() => onPage('products')}><Plus size={18} /> Cadastrar produto</button><button className="secondary" onClick={() => onPage('entrada')}><ArrowDownCircle size={18} /> Registrar entrada</button></div></div> : <section className="grid2"><div className="panel"><div className="panelHead"><h2>Estoque baixo</h2><button className="link" onClick={() => onPage('stock')}>Ver estoque</button></div>{data.products.filter(p => p.stock > 0 && p.stock <= p.minStock).slice(0, 7).map(p => <div className="row" key={p.id}><b>{p.name}</b><span>{fmt(p.stock)} {p.unit}</span><em>mínimo {fmt(p.minStock)}</em></div>)}{!low && <Empty text="Nenhum alerta de estoque no momento." />}</div><div className="panel"><div className="panelHead"><h2>Últimas movimentações</h2><button className="link" onClick={() => onPage('history')}>Ver histórico</button></div>{recent.map(m => <div className="row" key={m.id}><b>{m.product}</b><span className={m.type}>{m.type.toUpperCase()}</span><em>{fmt(m.quantity)}</em></div>)}{!recent.length && <Empty text="Nenhuma movimentação registrada." />}</div></section>}</> }

function Dashboard({ data, onPage }) { const low = data.products.filter(p => p.stock <= p.minStock).length; const cats = new Set(data.products.map(p => p.category)).size; const recent = data.movements.slice(0, 5); return <><section className="cards"><Card title="Produtos cadastrados" value={data.products.length} icon={Package} /><Card title="Categorias" value={cats} icon={ClipboardList} /><Card title="Estoque baixo" value={low} icon={AlertTriangle} /><Card title="Movimentações" value={data.movements.length} icon={History} /></section><section className="grid2"><div className="panel"><div className="panelHead"><h2>Estoque baixo</h2><button className="link" onClick={() => onPage('stock')}>Ver estoque</button></div>{data.products.filter(p => p.stock <= p.minStock).slice(0, 7).map(p => <div className="row" key={p.id}><b>{p.name}</b><span>{fmt(p.stock)} {p.unit}</span><em>mínimo {fmt(p.minStock)}</em></div>)}{!low && <Empty text="Nenhum produto com estoque baixo." />}</div><div className="panel"><div className="panelHead"><h2>Últimas movimentações</h2><button className="link" onClick={() => onPage('history')}>Ver histórico</button></div>{recent.map(m => <div className="row" key={m.id}><b>{m.product}</b><span className={m.type}>{m.type.toUpperCase()}</span><em>{fmt(m.quantity)}</em></div>)}{!recent.length && <Empty text="Ainda não existem movimentações registradas." />}</div></section></> }
function Card({ title, value, icon: Icon }) { return <div className="card"><div><span>{title}</span><strong>{value}</strong></div><Icon size={26} /></div> }
function Products({ products, search, setSearch, onNew, onMove, onProductChange }) { const list = products.filter(p => normalize(p.name).includes(normalize(search))); return <><div className="toolbar"><div className="search"><Search size={18} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar produto..." /></div><button className="primary" onClick={onNew}><Plus size={18} /> Novo produto</button></div><Table products={list} onMove={onMove} onProductChange={onProductChange} /></> }
function Stock({ products, onMove, onProductChange }) { return <><div className="notice">Clique em <b>Entrada</b> ou <b>Saída</b> para atualizar o estoque. Toda alteração gera histórico.</div><Table products={products} onMove={onMove} onProductChange={onProductChange} stock /></> }
function Table({ products, onMove, onProductChange, stock }) { return <div className="tableWrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Fornecedor</th><th>Unidade</th><th>Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody>{products.map(p => { const currentStock = Number(p.stock || 0); const minimumStock = Number(p.minStock || 0); const status = currentStock <= 0 ? 'Sem estoque' : currentStock <= minimumStock ? 'Baixo' : 'Normal'; return <tr key={p.id}><td><b>{p.name}</b></td><td>{p.category}</td><td>{p.supplier}</td><td>{p.unit}</td><td>{fmt(currentStock)}</td><td><span className={'badge ' + status.replace(' ', '')}>{status}</span></td><td><ProductActions product={p} onMove={onMove} onProductChange={onProductChange} /></td></tr> })}</tbody></table>{!products.length && <Empty text="Nenhum produto encontrado." />}</div> }
function MovementPage({ type, movements, onNew }) { const list = movements.filter(m => m.type === type); return <><div className="toolbar"><div><h2>{type === 'entrada' ? 'Entradas registradas' : 'Saídas registradas'}</h2><p>Todos os registros ficam disponíveis no histórico.</p></div><button className="primary" onClick={onNew}><Plus size={18} /> Nova {type === 'entrada' ? 'entrada' : 'saída'}</button></div><MovementList movements={list} /></> }
function MovementList({ movements }) { return <div className="panel list">{movements.map(m => <div className="movement" key={m.id}><div><b>{m.product}</b><span>{m.date} às {m.time} · {m.user}</span>{m.note && <small>{m.note}</small>}</div><strong className={m.type}>{m.type === 'entrada' ? '+' : '-'} {fmt(m.quantity)}</strong></div>)}{!movements.length && <Empty text="Nenhum registro encontrado." />}</div> }
function Weekly({ orders }) { return <div className="panel"><div className="panelHead"><div><h2>Controle de empenhos e recebimentos</h2><p>Baseado na planilha de carnes enviada.</p></div></div><div className="tableWrap"><table><thead><tr><th>Produto</th><th>Empenhado</th><th>Total recebido</th><th>Restante</th><th>Recebimentos</th></tr></thead><tbody>{orders.map(o => { const total = o.receipts.reduce((s, x) => s + x[1], 0); return <tr key={o.product}><td><b>{o.product}</b></td><td>{fmt(o.ordered)} kg</td><td>{fmt(total)} kg</td><td><b>{fmt(o.ordered - total)} kg</b></td><td>{o.receipts.map(r => `${r[0].split('-').reverse().join('/')} · ${r[1]} kg`).join(' | ')}</td></tr> })}</tbody></table></div></div> }
function Monthly({ movements }) { const month = new Date().toISOString().slice(0, 7); const list = movements.filter(m => m.date?.startsWith(month)); const entries = list.filter(m => m.type === 'entrada').reduce((s, m) => s + m.quantity, 0); const exits = list.filter(m => m.type === 'saida').reduce((s, m) => s + m.quantity, 0); return <><section className="cards"><Card title="Entradas no mês" value={fmt(entries)} icon={ArrowDownCircle} /><Card title="Saídas no mês" value={fmt(exits)} icon={ArrowUpCircle} /><Card title="Movimentações" value={list.length} icon={History} /></section><div className="panel"><h2>Movimentações do mês atual</h2><MovementList movements={list} /></div></> }
function HistoryPage({ movements }) { const [q, setQ] = useState(''); const list = movements.filter(m => normalize(`${m.product} ${m.user} ${m.type}`).includes(normalize(q))); return <><div className="toolbar"><div className="search"><Search size={18} /><input placeholder="Buscar no histórico..." value={q} onChange={e => setQ(e.target.value)} /></div></div><MovementList movements={list} /></> }
function Suppliers({ products }) { const groups = Object.entries(products.reduce((a, p) => { (a[p.supplier] ??= []).push(p); return a }, {})).sort((a, b) => a[0].localeCompare(b[0], 'pt-BR')); return <div className="supplierGrid">{groups.map(([name, ps]) => <div className="panel" key={name}><h2>{name}</h2><p>{ps.length} produto(s)</p><div className="chips">{ps.map(p => <span key={p.id}>{p.name}</span>)}</div></div>)}</div> }
function LegacyModal({ modal, products, onClose, onSave, onAddProduct }) { const [f, setF] = useState({ productId: modal.productId || products[0]?.id, type: modal.type, quantity: '', date: new Date().toISOString().slice(0, 10), note: '', name: '', category: 'Hortifruti', supplier: '', unit: 'kg', minStock: 10 }); const change = (k, v) => setF({ ...f, [k]: v }); const isNew = modal.type === 'newProduct'; return <div className="overlay"><div className="modal"><button className="close" onClick={onClose}><X /></button><h2>{isNew ? 'Novo produto' : f.type === 'entrada' ? 'Registrar entrada' : f.type === 'saida' ? 'Registrar saída' : 'Ajustar estoque'}</h2>{isNew ? <><label>Nome<input value={f.name} onChange={e => change('name', e.target.value)} /></label><label>Categoria<input value={f.category} onChange={e => change('category', e.target.value)} /></label><label>Fornecedor<input value={f.supplier} onChange={e => change('supplier', e.target.value)} /></label><div className="two"><label>Unidade<input value={f.unit} onChange={e => change('unit', e.target.value)} /></label><label>Estoque mínimo<input type="number" value={f.minStock} onChange={e => change('minStock', e.target.value)} /></label></div><button className="primary full" onClick={() => f.name.trim() && onAddProduct(f)}>Cadastrar produto</button></> : <><label>Produto<select value={f.productId} onChange={e => change('productId', e.target.value)}>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="two"><label>Quantidade<input type="number" min="0" value={f.quantity} onChange={e => change('quantity', e.target.value)} /></label><label>Data<input type="date" value={f.date} onChange={e => change('date', e.target.value)} /></label></div><label>Observação<textarea value={f.note} onChange={e => change('note', e.target.value)} placeholder="Ex.: número da NF ou destino" /></label><button className="primary full" onClick={() => Number(f.quantity) > 0 && onSave(f)}>Salvar movimentação</button></>}</div></div> }
function Empty({ text }) { return <div className="empty">{text}</div> }; const normalize = s => (s || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
createRoot(document.getElementById('root')).render(<App />);
