import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, Package, ArrowDownCircle, ArrowUpCircle, History, Truck, ClipboardList, Plus, Search, LogOut, Menu, X, AlertTriangle, CalendarDays, SlidersHorizontal} from 'lucide-react';
import './styles.css';

const STORAGE='itabera-controle-alimentos-v1';
const initialProducts=[
  ['ABACATE','Hortifruti','COOPAFASP','kg'],['ABOBRINHA','Hortifruti','AGROVIDA','kg'],['ABÓBORA PESCOÇO','Hortifruti','AGROVIDA','kg'],['ACELGA','Hortifruti','COOPAFASP','kg'],['AÇUCAR','Alimentos Secos','MERCADO CENTRAL','kg'],['ADOÇANTE','Alimentos Secos','STS','un'],['ALFACE','Hortifruti','AGROVIDA','kg'],['AMIDO DE MILHO','Alimentos Secos','FEC','kg'],['ARROZ INTEGRAL','Alimentos Secos','FEC','kg'],['AVEIA EM FARINHA','Alimentos Secos','FEC','kg'],['AVEIA EM FLOCOS','Alimentos Secos','FEC','kg'],['BANANA NANICA','Hortifruti','COOPAFASP','kg'],['BANANA PRATA','Hortifruti','COOPAFASP','kg'],['BATATA DOCE','Hortifruti','AGROVIDA','kg'],['BETERRABA','Hortifruti','AGROVIDA','kg'],['BRÓCOLIS','Hortifruti','AGROVIDA','kg'],['CEBOLA','Hortifruti','AGROVIDA','kg'],['CEBOLINHA','Hortifruti','AGROVIDA','kg'],['CENOURA','Hortifruti','AGROVIDA','kg'],['CHUCHU','Hortifruti','COOPAFASP','kg'],['COUVE','Hortifruti','AGROVIDA','kg'],['COUVE-FLOR','Hortifruti','COOPAFASP','kg'],['FEIJÃO CARIOCA','Alimentos Secos','DA TERRA','kg'],['LARANJA','Hortifruti','COOPAFASP','kg'],['LEITE','Laticínios','ÁGUA PRETA','L'],['MAÇÃ','Hortifruti','MARCIA CORREA','kg'],['MANDIOCA','Hortifruti','AGROVIDA','kg'],['MAMÃO FORMOSO','Hortifruti','LUIZ RAFAEL','kg'],['MELANCIA','Hortifruti','AGROVIDA','kg'],['MEXERICA','Hortifruti','COOPAFASP','kg'],['MILHO VERDE','Hortifruti','AGROVIDA','kg'],['MÚSCULO BOVINO','Carnes','FRIGOBOI','kg'],['PATINHO EM CUBOS','Carnes','FRIGOBOI','kg'],['PATINHO EM ISCAS','Carnes','FRIGOBOI','kg'],['PATINHO MOIDO','Carnes','FRIGOBOI','kg'],['PEITO DE FRANGO EM CUBOS','Carnes','FRIGOBOI','kg'],['PEPINO','Hortifruti','AGROVIDA','kg'],['PERNIL SUINO EM CUBOS','Carnes','FRIGOBOI','kg'],['PITAYA','Hortifruti','COOPAFASP','kg'],['REQUEIJÃO','Laticínios','ÁGUA PRETA','kg'],['REPOLHO','Hortifruti','AGROVIDA','kg'],['SALSINHA','Hortifruti','AGROVIDA','kg'],['SOBRECOXA EM CUBOS','Carnes','FRIGOBOI','kg'],['TOMATE','Hortifruti','COOPAFASP','kg']
].sort((a,b)=>a[0].localeCompare(b[0],'pt-BR')).map((p,i)=>({id:i+1,name:p[0],category:p[1],supplier:p[2],unit:p[3],stock:0,minStock:10}));
const initialOrders=[
 {product:'MÚSCULO BOVINO',ordered:800,receipts:[['2026-06-03',108],['2026-06-11',74],['2026-06-18',70],['2026-06-25',156]]},
 {product:'PATINHO EM CUBOS',ordered:1000,receipts:[['2026-06-10',264],['2026-06-18',188],['2026-06-25',68]]},
 {product:'PATINHO EM ISCAS',ordered:800,receipts:[['2026-06-03',304],['2026-06-11',228],['2026-06-25',250]]},
 {product:'PATINHO MOIDO',ordered:1500,receipts:[['2026-06-03',396],['2026-06-10',396],['2026-06-11',324],['2026-06-25',560]]},
 {product:'SOBRECOXA EM CUBOS',ordered:1500,receipts:[['2026-06-03',449],['2026-06-10',449],['2026-06-11',384],['2026-06-18',218]]},
 {product:'PERNIL SUINO EM CUBOS',ordered:1500,receipts:[['2026-06-03',591],['2026-06-10',591],['2026-06-18',318]]},
 {product:'PEITO DE FRANGO EM CUBOS',ordered:1000,receipts:[['2026-06-03',416],['2026-06-10',416],['2026-06-18',290]]}
];
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||{products:initialProducts,movements:[],orders:initialOrders}}catch{return {products:initialProducts,movements:[],orders:initialOrders}}}
function App(){
 const [data,setData]=useState(load); const [page,setPage]=useState('dashboard'); const [search,setSearch]=useState(''); const [modal,setModal]=useState(null); const [menu,setMenu]=useState(false); const [logged,setLogged]=useState(false); const [user,setUser]=useState('');
 useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(data)),[data]);
 const saveMovement=(form)=>{const p=data.products.find(x=>x.id===Number(form.productId)); if(!p)return; const qty=Number(form.quantity); const delta=form.type==='entrada'?qty:form.type==='saida'?-qty:qty-p.stock; if(form.type==='saida'&&qty>p.stock){alert('A saída não pode ser maior que o estoque atual.');return;} const products=data.products.map(x=>x.id===p.id?{...x,stock:Math.max(0,x.stock+delta)}:x); const movements=[{id:crypto.randomUUID(),date:form.date||new Date().toISOString().slice(0,10),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),product:p.name,type:form.type,quantity:qty,delta,user:user||'Usuária',note:form.note||'',supplier:p.supplier},...data.movements]; setData({...data,products,movements});setModal(null)};
 if(!logged)return <Login onLogin={(name)=>{setUser(name);setLogged(true)}}/>;
 const nav=[['dashboard','Dashboard',LayoutDashboard],['products','Produtos',Package],['stock','Estoque',ClipboardList],['entrada','Entradas',ArrowDownCircle],['saida','Saídas',ArrowUpCircle],['weekly','Controle Semanal',CalendarDays],['monthly','Controle Mensal',SlidersHorizontal],['history','Histórico',History],['suppliers','Fornecedores',Truck]];
 const content=()=>{switch(page){case'dashboard':return <Dashboard data={data} onPage={setPage}/>;case'products':return <Products products={data.products} search={search} setSearch={setSearch} onNew={()=>setModal({type:'newProduct'})} onMove={(type,id)=>setModal({type,productId:id})}/>;case'stock':return <Stock products={data.products} onMove={(type,id)=>setModal({type,productId:id})}/>;case'entrada':return <MovementPage type="entrada" movements={data.movements} onNew={()=>setModal({type:'entrada'})}/>;case'saida':return <MovementPage type="saida" movements={data.movements} onNew={()=>setModal({type:'saida'})}/>;case'weekly':return <Weekly orders={data.orders}/>;case'monthly':return <Monthly movements={data.movements}/>;case'history':return <HistoryPage movements={data.movements}/>;case'suppliers':return <Suppliers products={data.products}/>;default:return null}};
 return <div className="app"><aside className={menu?'open':''}><div className="brand"><img src="/logo-prefeitura.png"/><div><b>Controle de Alimentação</b><small>Prefeitura de Itaberá</small></div><button className="icon mobile" onClick={()=>setMenu(false)}><X/></button></div>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><Icon size={19}/>{label}</button>)}<div className="sideBottom"><span>Logada como</span><b>{user}</b><button onClick={()=>setLogged(false)}><LogOut size={18}/> Sair</button></div></aside><main><header><button className="icon mobile" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{nav.find(n=>n[0]===page)?.[1]}</h1><p>Gestão de estoque e recebimento de alimentos</p></div><div className="shared">● Dados compartilhados</div></header>{content()}</main>{modal&&<Modal modal={modal} products={data.products} onClose={()=>setModal(null)} onSave={saveMovement} onAddProduct={(p)=>{setData({...data,products:[...data.products,{...p,id:Date.now(),stock:0,minStock:Number(p.minStock||10)}].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))});setModal(null)}}/>}</div>
}
function Login({onLogin}){const[n,setN]=useState('');return <div className="login"><div className="loginCard"><img src="/logo-prefeitura.png"/><h1>Controle de Alimentação</h1><p>Gestão de estoque e recebimento</p><input placeholder="Nome da usuário" value={n} onChange={e=>setN(e.target.value)}/><input type="password" placeholder="Senha"/><button onClick={()=>n.trim()?onLogin(n):alert('Informe o nome da usuária.')}>Entrar</button><small>Versão inicial local. Configure o Supabase para autenticação e dados compartilhados em produção.</small></div></div>}
const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(n);
function Dashboard({data,onPage}){const low=data.products.filter(p=>p.stock<=p.minStock).length;const cats=new Set(data.products.map(p=>p.category)).size;const recent=data.movements.slice(0,5);return <><section className="cards"><Card title="Produtos cadastrados" value={data.products.length} icon={Package}/><Card title="Categorias" value={cats} icon={ClipboardList}/><Card title="Estoque baixo" value={low} icon={AlertTriangle}/><Card title="Movimentações" value={data.movements.length} icon={History}/></section><section className="grid2"><div className="panel"><div className="panelHead"><h2>Estoque baixo</h2><button className="link" onClick={()=>onPage('stock')}>Ver estoque</button></div>{data.products.filter(p=>p.stock<=p.minStock).slice(0,7).map(p=><div className="row" key={p.id}><b>{p.name}</b><span>{fmt(p.stock)} {p.unit}</span><em>mínimo {fmt(p.minStock)}</em></div>)}{!low&&<Empty text="Nenhum produto com estoque baixo."/>}</div><div className="panel"><div className="panelHead"><h2>Últimas movimentações</h2><button className="link" onClick={()=>onPage('history')}>Ver histórico</button></div>{recent.map(m=><div className="row" key={m.id}><b>{m.product}</b><span className={m.type}>{m.type.toUpperCase()}</span><em>{fmt(m.quantity)}</em></div>)}{!recent.length&&<Empty text="Ainda não existem movimentações registradas."/>}</div></section></>}
function Card({title,value,icon:Icon}){return <div className="card"><div><span>{title}</span><strong>{value}</strong></div><Icon size={26}/></div>}
function Products({products,search,setSearch,onNew,onMove}){const list=products.filter(p=>normalize(p.name).includes(normalize(search)));return <><div className="toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto..."/></div><button className="primary" onClick={onNew}><Plus size={18}/> Novo produto</button></div><Table products={list} onMove={onMove}/></>}
function Stock({products,onMove}){return <><div className="notice">Clique em <b>Entrada</b> ou <b>Saída</b> para atualizar o estoque. Toda alteração gera histórico.</div><Table products={products} onMove={onMove} stock/></>}
function Table({products,onMove,stock}){return <div className="tableWrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Fornecedor</th><th>Unidade</th><th>Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody>{products.map(p=>{const status=p.stock===0?'Sem estoque':p.stock<=p.minStock?'Baixo':'Normal';return <tr key={p.id}><td><b>{p.name}</b></td><td>{p.category}</td><td>{p.supplier}</td><td>{p.unit}</td><td>{fmt(p.stock)}</td><td><span className={'badge '+status.replace(' ','')}>{status}</span></td><td className="actions"><button onClick={()=>onMove('entrada',p.id)}>Entrada</button><button onClick={()=>onMove('saida',p.id)}>Saída</button></td></tr>})}</tbody></table>{!products.length&&<Empty text="Nenhum produto encontrado."/>}</div>}
function MovementPage({type,movements,onNew}){const list=movements.filter(m=>m.type===type);return <><div className="toolbar"><div><h2>{type==='entrada'?'Entradas registradas':'Saídas registradas'}</h2><p>Todos os registros ficam disponíveis no histórico.</p></div><button className="primary" onClick={onNew}><Plus size={18}/> Nova {type==='entrada'?'entrada':'saída'}</button></div><MovementList movements={list}/></>}
function MovementList({movements}){return <div className="panel list">{movements.map(m=><div className="movement" key={m.id}><div><b>{m.product}</b><span>{m.date} às {m.time} · {m.user}</span>{m.note&&<small>{m.note}</small>}</div><strong className={m.type}>{m.type==='entrada'?'+':'-'} {fmt(m.quantity)}</strong></div>)}{!movements.length&&<Empty text="Nenhum registro encontrado."/>}</div>}
function Weekly({orders}){return <div className="panel"><div className="panelHead"><div><h2>Controle de empenhos e recebimentos</h2><p>Baseado na planilha de carnes enviada.</p></div></div><div className="tableWrap"><table><thead><tr><th>Produto</th><th>Empenhado</th><th>Total recebido</th><th>Restante</th><th>Recebimentos</th></tr></thead><tbody>{orders.map(o=>{const total=o.receipts.reduce((s,x)=>s+x[1],0);return <tr key={o.product}><td><b>{o.product}</b></td><td>{fmt(o.ordered)} kg</td><td>{fmt(total)} kg</td><td><b>{fmt(o.ordered-total)} kg</b></td><td>{o.receipts.map(r=>`${r[0].split('-').reverse().join('/')} · ${r[1]} kg`).join(' | ')}</td></tr>})}</tbody></table></div></div>}
function Monthly({movements}){const month=new Date().toISOString().slice(0,7);const list=movements.filter(m=>m.date?.startsWith(month));const entries=list.filter(m=>m.type==='entrada').reduce((s,m)=>s+m.quantity,0);const exits=list.filter(m=>m.type==='saida').reduce((s,m)=>s+m.quantity,0);return <><section className="cards"><Card title="Entradas no mês" value={fmt(entries)} icon={ArrowDownCircle}/><Card title="Saídas no mês" value={fmt(exits)} icon={ArrowUpCircle}/><Card title="Movimentações" value={list.length} icon={History}/></section><div className="panel"><h2>Movimentações do mês atual</h2><MovementList movements={list}/></div></>}
function HistoryPage({movements}){const [q,setQ]=useState('');const list=movements.filter(m=>normalize(`${m.product} ${m.user} ${m.type}`).includes(normalize(q)));return <><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Buscar no histórico..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><MovementList movements={list}/></>}
function Suppliers({products}){const groups=Object.entries(products.reduce((a,p)=>{(a[p.supplier]??=[]).push(p);return a},{})).sort((a,b)=>a[0].localeCompare(b[0],'pt-BR'));return <div className="supplierGrid">{groups.map(([name,ps])=><div className="panel" key={name}><h2>{name}</h2><p>{ps.length} produto(s)</p><div className="chips">{ps.map(p=><span key={p.id}>{p.name}</span>)}</div></div>)}</div>}
function Modal({modal,products,onClose,onSave,onAddProduct}){const [f,setF]=useState({productId:modal.productId||products[0]?.id,type:modal.type,quantity:'',date:new Date().toISOString().slice(0,10),note:'',name:'',category:'Hortifruti',supplier:'',unit:'kg',minStock:10});const change=(k,v)=>setF({...f,[k]:v});const isNew=modal.type==='newProduct';return <div className="overlay"><div className="modal"><button className="close" onClick={onClose}><X/></button><h2>{isNew?'Novo produto':f.type==='entrada'?'Registrar entrada':f.type==='saida'?'Registrar saída':'Ajustar estoque'}</h2>{isNew?<><label>Nome<input value={f.name} onChange={e=>change('name',e.target.value)}/></label><label>Categoria<input value={f.category} onChange={e=>change('category',e.target.value)}/></label><label>Fornecedor<input value={f.supplier} onChange={e=>change('supplier',e.target.value)}/></label><div className="two"><label>Unidade<input value={f.unit} onChange={e=>change('unit',e.target.value)}/></label><label>Estoque mínimo<input type="number" value={f.minStock} onChange={e=>change('minStock',e.target.value)}/></label></div><button className="primary full" onClick={()=>f.name.trim()&&onAddProduct(f)}>Cadastrar produto</button></>:<><label>Produto<select value={f.productId} onChange={e=>change('productId',e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="two"><label>Quantidade<input type="number" min="0" value={f.quantity} onChange={e=>change('quantity',e.target.value)}/></label><label>Data<input type="date" value={f.date} onChange={e=>change('date',e.target.value)}/></label></div><label>Observação<textarea value={f.note} onChange={e=>change('note',e.target.value)} placeholder="Ex.: número da NF ou destino"/></label><button className="primary full" onClick={()=>Number(f.quantity)>0&&onSave(f)}>Salvar movimentação</button></>}</div></div>}
function Empty({text}){return <div className="empty">{text}</div>};const normalize=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
createRoot(document.getElementById('root')).render(<App/>);
